### ISSUE TITLE
Not able to create snapshot of a model using dbt-trino==1.7.1

### ISSUE THREAD

**Issue by AviKasliwal04** [starburstdata/dbt-trino#386] opened 2024-02-25 14:20 UTC
### Expected behavior

Snapshot of model should be created.

The log should say something on the lines of:
`1 of 1 OK snapshotted _<model_name>_......................................... [SUCCESS in 20.57s]`

### Actual behavior

Getting database error:

```
Database Error in snapshot _<model_name>_ (snapshots/_<model_name>_snapshot.sql)
  TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 3:76: mismatched input '__dbt_tmp'. Expecting: '.', <EOF>", query_id=_<query_id>_)
```
  
 Actual query fired:
` DROP TABLE IF EXISTS "<catalog_or_db_name>"."<schema_name>"."<model_name>"__dbt_tmp`

Should have fired:
` DROP TABLE IF EXISTS "<catalog_or_db_name>"."<schema_name>"."<model_name>__dbt_tmp"`

### Steps To Reproduce

Create a simple model and then a snapshot for that model.

dbt-core == 1.7.1
dbt-trino == 1.7.1
trino version == 438 [Should I bring it down to 435?]

### Log output/Screenshots

![Screenshot 2024-02-25 at 7 42 59 PM](https://github.com/starburstdata/dbt-trino/assets/142870503/65eea8a8-4196-402f-86f7-9421f6e3db9d)

### Operating System

Mac OS 14 Sanoma

### dbt version

1.7.1

### Trino Server version

438

### Python version

3.9.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by damian3031** [comment] 2024-02-29 10:38
I'm trying to reproduce this behaviour, but so far, I've had no luck.

So, it fails exactly at
`DROP TABLE IF EXISTS "<catalog_or_db_name>"."<schema_name>"."<model_name>"__dbt_tmp`

but previously CREATE TABLE succeded, appending `__dbt_tmp` suffix properly to model name?

**Comment by AviKasliwal04** [comment] 2024-03-06 11:46
I was able to find a way around it by modifying the `run_hooks` macro. added one `run_hooks.sql` file in my macros folder with the following code snippet


```jinja2
{% macro run_hooks(hooks, inside_transaction=True) %}
  {% for hook in hooks | selectattr('transaction', 'equalto', inside_transaction)  %}
    {% if not inside_transaction and loop.first %}
      {% call statement(auto_begin=inside_transaction) %}
        commit;
      {% endcall %}
    {% endif %}
    {% set rendered = render(hook.get('sql')) | trim | replace('"', '') %} -- to replace "" from table name
    {% if (rendered | length) > 0 %}
      {% call statement(auto_begin=inside_transaction) %}
        {{ rendered }}
      {% endcall %}
    {% endif %}
  {% endfor %}
{% endmacro %}


{% macro make_hook_config(sql, inside_transaction) %}
    {{ tojson({"sql": sql, "transaction": inside_transaction}) }}
{% endmacro %}


{% macro before_begin(sql) %}
    {{ make_hook_config(sql, inside_transaction=False) }}
{% endmacro %}


{% macro in_transaction(sql) %}
    {{ make_hook_config(sql, inside_transaction=True) }}
{% endmacro %}


{% macro after_commit(sql) %}
    {{ make_hook_config(sql, inside_transaction=False) }}
{% endmacro %}
```

**Comment by AviKasliwal04** [comment] 2024-05-30 06:06
@damian3031  the above solution worked for my case, but is it the best way, or there is some other easier way, may be by updating some configurations - could not find alter way in docs :/

**Comment by hovaesco** [comment] 2024-07-23 11:52
Closing as the issue is not reproducible.

**Closed by hovaesco** 2024-07-23 11:52 UTC
Labels: bug
