### ISSUE TITLE
dbt-trino 1.0.3 needs to use a compatibility pin on dbt-core 1.0

### ISSUE THREAD

**Issue by dataders** [starburstdata/dbt-trino#222] opened 2023-02-01 22:58 UTC
`~=` instead of `==`. We’d then very much like a new patch release of dbt-trino 1.0

https://github.com/starburstdata/dbt-trino/blob/bd3f4a529c1467187279d1c8e9ae3cb505d19cff/setup.py#L62

**Comment by hovaesco** [comment] 2023-02-14 17:41
Duplicate of https://github.com/starburstdata/dbt-trino/issues/221

**Closed by hovaesco** 2023-02-14 17:41 UTC
