### ISSUE TITLE
issue with big seed file

### ISSUE THREAD

**Issue by bachng2017** [starburstdata/dbt-trino#16] opened 2021-11-18 09:07 UTC
error whle seeding a big csv file:
```
Runtime Error in seed com_event_log_info (data/<filename>csv)
  TrinoUserError(type=USER_ERROR, name=QUERY_TEXT_TOO_LARGE, message="Query text length (1380022) exceeds the maximum length (1000000)", query_id=20211116_121112_10193_2mbb4)
```

same file could be seeded without problem with dbt-presto driver.

**Comment by hovaesco** [comment] 2021-11-18 09:18
It's probably related to: https://github.com/starburstdata/dbt-trino/commit/ef05a4ea4c0ee4dd5806258c8434b2e9b0684bc6

I will verify that and come back to you.

**Comment by findinpath** [comment] 2021-11-18 10:28
I think we should make the batch size configurable

https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/seeds/helpers.sql#L60-L62

I see that by default it is `10000`. Either we make it `1000` or maybe get it to a configurable value.
I'll ask on the chat about the possibility of making this setting configurable by the user.

**Comment by findinpath** [comment] 2021-11-18 10:30
@bachng2017 thank you for reporting this issue.
This is likely caused by the fact that the `INSERT` query which is executed against Trino is too long.
We'll address this issue by limiting/making configurable the batch size of the values inserted into Trino.

**Comment by jtcohen6** [comment] 2021-11-18 11:00
Reimplementing the default batch size makes a lot of sense:
```sql
{% macro trino__get_batch_size() %}
  {{ return(1000) }}
{% endmacro %}
```
Users can still override that in their own projects if they want a different value, by defining a local macro named `get_batch_size()`, `default__get_batch_size()`, or `trino__get_batch_size()`.

**Comment by hovaesco** [comment] 2021-11-18 11:14
PR with the change: https://github.com/starburstdata/dbt-trino/pull/18

**Comment by hovaesco** [comment] 2021-11-22 09:51
Closing the issue. The fix will be available in the next release. Default value of batch_size changed to 1000. There is an instruction in README how to override default value if needed.

**Closed by hovaesco** 2021-11-22 09:51 UTC
